---
- name: Criando bucket s3
  aws_s3:
    bucket: "site-estatico-{{ bucket_name }}"
    region: "{{ region }}"
    mode: create
    tags:
          Name: "Site estatico"
          Environment: "Production"
    permission: public-read
    object: []
        

- name: Configurando Website
  s3_website:
    index_document: "index.html"
    error_document: "error.html"
    bucket: "static-site-{{ bucket_name }}"
    region: "{{ region }}"