---
- name: Criando bucket s3
  s3_bucket:
    name: "site-estatico-{{ bucket_name }}"
    state: present
    region: "{{ region }}"
    tags:
          Name: "Site estatico"
          Environment: "Production"        

- name: Configurando Website
  s3_website:
    bucket: "static-site-{{ bucket_name }}"
    index_document: "index.html"
    error_document: "error.html"
    region: "{{ region }}"