---
- name: Criando bucket s3
  s3_bucket:
    name: "{{ bucket_name }}"
    state: present
    region: "{{ region }}"
    tags:
          Name: "Site estatico"
          Environment: "Prudução"
    policy: | 
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::{{ bucket_name }}/*"
          }
        ]
      }

- name: Configurando Website
  s3_website:
    name: "{{ bucket_name }}"
    suffix: "index.html"
    error_key: "404.html"
    region: "{{ region }}"
    state: present

- name: Criando objeto index no bucket s3
  s3_object:
    bucket: "{{ bucket_name }}"
    src: "./index.html"
    mode: put

- name: Criando objeto error no bucket s3
  s3_object:
    bucket: "{{ bucket_name }}"
    src: "./404.html"
    mode: put
