---
- name: Criando bucket s3
  s3_bucket:
    name: "{{ bucket_name }}"
    state: present
    region: "{{ region }}"
    tags:
          Name: "Site estatico"
          Environment: "Production"        

- name: Configurando Website
  s3_website:
    name: "{{ bucket_name }}"
    suffix: "index.html"
    error_key: "error.html"
    region: "{{ region }}"
    state: present