---
- name: Criando bucket s3
  amazon.aws.s3_bucket:
    name: "{{ bucket_name | string }}"
    state: present
    region: "{{ region }}"
    tags:
      Name: "Site estatico"
      Environment: "Production"
    public_access:
      restrict_public_buckets: false
      ignore_public_acls: false
      block_public_acls: false
      block_public_policy: false
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
              "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::{{ bucket_name }}/*"
          }
        ]
      }

- name: Configurando Website
  s3_website:
    name: "{{ bucket_name }}"
    suffix: "index.html"
    error_key: "404.html"
    region: "{{ region }}"
    state: present

- name: Criando objeto index no bucket s3
  amazon.aws.s3_object:
    bucket: "{{ bucket_name }}"
    object: index.html
    src: "../index.html"
    mode: put

- name: Criando objeto error no bucket s3
  amazon.aws.s3_object:
    bucket: "{{ bucket_name }}"
    object: 404.html
    src: "../404.html"
    mode: put
