---
- name: Excluindo Bucket S3
  hosts: localhost
  vars_files:
  - provision/vars/main.yml 
  gather_facts: no
  tasks:
  - name: Configurando Website
    s3_website:
      name: "{{ bucket_name }}"
      region: "{{ region }}"
      state: absent

  - name: Excluindo objeto index no bucket s3
    amazon.aws.s3_object:
      bucket: "{{ bucket_name }}"
      object: index.html
      mode: delobj

  - name: Excluindo objeto error no bucket s3
    amazon.aws.s3_object:
      bucket: "{{ bucket_name }}"
      object: 404.html
      mode: delobj

  - name: Excluindo bucket s3
    amazon.aws.s3_bucket:
      name: "{{ bucket_name | string }}"
      state: absent
      region: "{{ region }}"